blueprints/user.py
# redirect 重定向静态网页，user.py是视图函数
from flask import (Blueprint,
                   render_template,
                   request, redirect, url_for, session, jsonify,flash)
from exts import mail, db
from flask_mail import Message
from models import EmailcpatchaModel, UserModel
import string
import random
from datetime import datetime
from .forms import RegisterForm, LoginForm
from werkzeug.security import generate_password_hash, check_password_hash

# 对应的访问的url的前缀   http://127.0.0.1:5000/user
bp = Blueprint('user', __name__, url_prefix='/user')


# 设置在user蓝图下的login登录界面
@bp.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'GET':
        return render_template('login.html')
    else:
        form = LoginForm(request.form)
        if form.validate():
            email = form.email.data
            password = form.password.data
            user = UserModel.query.filter_by(email=email).first()
            if user and check_password_hash(user.password, password):
                # 获取表user 的id
                session['user_id'] = user.id
                return redirect('/')
            else:
                flash('邮箱和密码不匹配')
                return redirect(url_for('user.login'))
        else:
            flash('邮箱或者密码格式错误')
            return redirect(url_for('user.login'))


@bp.route('/register', methods=['GET', 'POST'])
def register():
    if request.method == 'GET':
        return render_template('register.html')
    else:
        # 获取前端页面register.html文件中的form表单传入的内容
        form = RegisterForm(request.form)
        if form.validate():
            email = form.email.data
            # 在form.py设置了对应的验证码的举措，这部分的captcha验证可以省略
            # captcha = form.captcha.data
            username = form.username.data
            password = form.password.data
            # 获取哈希密码转化后的密码
            hash_password = generate_password_hash(password)
            user = UserModel(email=email, username=username, password=hash_password)
            db.session.add(user)
            db.session.commit()
            return redirect(url_for('user.login'))
        else:
            return redirect(url_for('user.register'))


@bp.route('/mail')
def sender():
    message = Message(
        subject='邮箱测试',
        recipients=['zhizhihua9808@163.com', '919006684@qq.com', 'sj13652388474@outlook.com'],
        body='测试'
    )
    mail.send(message)
    return '发送成功'


@bp.route('/captcha', methods=['POST'])
# 还没设置好注册页面的时候使用下面的链接访问
# http://127.0.0.1:5000/user/captcha?email=919006684@qq.com
def getemaildaptcha():
    # get请求获取对应的邮箱
    # email = request.args.get('email')
    # post请求获取对应的邮箱
    email = request.form.get('email')
    # 获取数字和字母的库check
    check = string.digits + string.ascii_letters
    # 从check库获取随机四位的验证码
    captcha = ''.join(random.sample(check, 4))
    if email:
        message = Message(
            subject='稚至花',
            # recipients=['zhizhihua9808@163.com', '919006684@qq.com', 'sj13652388474@outlook.com'],
            recipients=[email],
            body=f'【稚至花科技有限公司】您在本公司注册的账号验证码是：【{captcha}】,请不要泄露给你身边的人哦☺！！'
        )
        # 发送message部分的内容
        mail.send(message)
        # 获取emailcaptcha表里面的email字段对应的邮箱的的第一条数据
        captchamodel = EmailcpatchaModel.query.filter_by(email=email).first()
        if captchamodel:
            # 如果数据库中存在验证码，则发送新的验证码captcha
            captchamodel.captcha = captcha
            # 发送新的内容之后要更新时间
            captchamodel.creat_time = datetime.now()
            # 上传到数据库中
            db.session.commit()
            # 不存在验证码则发送新的验证码
        else:
            captchamodel = EmailcpatchaModel(email=email, captcha=captcha)
            db.session.add(captchamodel)
            db.session.commit()
            # code 200在浏览器是访问请求正常的
        return jsonify({'code': 200})
    else:
        # 400 是客户端错误
        return jsonify({'code': 400, 'message': '请先传递邮箱！'})

#实现退出登录
@bp.route('/logout')
def logout():
    # 清除session所有的数据
    session.clear()
    return  redirect(url_for('user.login'))

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    {% block head %}{% endblock %}
    {#    url_for 老是忘记写，真的难受#}
    {#    filename 是指定对应的static文件下的bootstrap文件夹里面的bootstrap@4.6.min.css文件#}
    <link rel="stylesheet" href="{{ url_for('static',filename='bootstrap/bootstrap@4.6.min.css') }}">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <div class="spinner-grow text-dark  mr-5">
           <a class="navbar-brand" href="#"><h4>🚀稚至花</h4></a>
        </div>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse ml-4" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto ml-4">
                <li class="nav-item active">
                    <a class="nav-link ml-7" href="/">首页</a>
                </li>
                <li class="nav-item ml-4">
{#                    访问answer视图下的public_question html文件#}
                    <a class="nav-link" href="{{ url_for('answer.public_question') }}">发布帖子</a>
                </li>
                <li class="nav-item ml-5">
                    <form class="form-inline my-2 my-lg-0 ml-8">
                        <input class="form-control mr-sm-2" type="search" placeholder="输入关键词🖊" aria-label="搜索🔍">
                        <button class="btn btn-outline-success my-2 my-sm-0 ml-2" type="submit">Search🔍</button>
                    </form>
                </li>

            </ul>
            <ul class="navbar-nav mr-auto">
{#            登录情况下显示对应的账号名和注销#}
                {% if  user %}
                    <li class="nav-item active">
                        <span class ='nav-link'>{{user.username}}</span>
                    </li>
                    <li class="nav-item ">
                        <a class="nav-link" href="{{ url_for('user.logout')}}">注销</a>
                    </li>

{#                    没登录的情况下显示登录注册#}
                {% else %}
                    <li class="nav-item active">
                        <a class="nav-link ml-4" href="{{ url_for('user.register')}}">注册</a>
                    </li>
                    <li class="nav-item ">
                        <a class="nav-link" href="{{ url_for('user.login')}}">登录</a>
                    </li>
                
                {% endif %} 


            </ul>

        </div>
    </div>
</nav>
{% block body %}{% endblock %}
</body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block title %}
    🚀稚至花
{% endblock %}

{% block head %}

{% endblock %}

{% block  body %}

    <h1>首页内容待添加</h1>

{% endblock %}

templates/login.html
{% extends 'base.html' %}

{% block title %}
    🚀稚至花
{% endblock %}

{% block head %}

{% endblock %}

{% block  body %}

    <form METHOD="post" ACTION="{{ url_for('user.login') }}">>

        <div class="row mt-5">
            <div class="col-sm">

            </div>
            <div class="col-sm">
                <div class="form-group">

                    <label for="exampleInputEmail1">邮箱</label>
                    <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp"
                           name="email">
                    <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone
                        else.</small>

                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1">密码</label>
                    <input type="password" class="form-control" id="exampleInputPassword1" name="password">
                </div>
                {#                <div class="form-group form-check">#}
                {#                    <input type="checkbox" class="form-check-input" id="exampleCheck1">#}
                {#                    <label class="form-check-label" for="exampleCheck1">Check me out</label>#}
                {#                </div>#}
                {% for message in get_flashed_messages() %}
                    <div class="form-group">
                    <div class="text-danger">{{message}}</div>

                    </div>

                {% endfor %}

                <div class="form-group">

                    <button type="submit" class="btn btn-primary btn-block">Submit</button>
                </div>


            </div>
            <div class="col-sm">

            </div>
        </div>
        </div>

    </form>


{% endblock %}

templates/public_question.html
{% extends 'base.html' %}

{% block title %}
🚀稚至花
{% endblock %}

{% block body %}
    <div class="row" style="margin-top:  26px;">
    <div class="col"></div>
        <div class="col-8">
            <form action="{{ url_for('answer.public_question') }}" method="post">

                <div class="form-group">
                    <input type="text",name ='title'  class="form-control" placeholder="输入标题">
                </div>
                <div class="form-group">
                    <textarea name="content" id="questions" class="form-control"  rows="10" placeholder="请输入内容~~"></textarea>
                </div>
                <div class="form-group">

                        <button type="submit" class="btn btn-primary btn-block">发布问答</button>
                </div>

            </form>
        </div>
    <div class="col"></div>

    </div>


{% endblock %}

templates/register.html
{% extends 'base.html' %}

{% block title %}
    🚀稚至花
{% endblock %}

{% block head %}
    <script src="{{url_for('static',filename='jquery/jquery.3.6.min.js')}}"></script>
    <script src="{{url_for('static',filename='js/register.js')}}"></script>
{% endblock %}

{% block  body %}
{#    meehod 是表示请求的方法， action是表示你要把下面的输入的数据请求的内容发送到哪个页面，user表示的是蓝图的url_prefix 的地址#}
    <form METHOD="post" ACTION="{{ url_for('user.register')}}">

        <div class="row mt-5">
            <div class="col-sm">

            </div>
            <div class="col-sm">
                <div class="form-group">

                    <label for="exampleInputEmail1">邮箱</label>
                    <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" name="email">
                    <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone
                        else.</small>

                </div>
                <div class="form-group">

                    <label for="exampleInputEmail1">验证码</label>
                    <div class="input-group">
                        <input type="text" class="form-control" name="captcha">
                        <div class="input-group-append">
                            <button class="btn btn-outline-secondary" type="button" id ='captcha-btn'>获取验证码</button>
                        </div>
                    </div>
                <div class="form-group">

                    <label for="exampleInputEmail1">用户名</label>
                    <input type="text"  class="form-control" name="username">

                </div>

                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1">密码</label>
                    <input type="password" class="form-control" id="exampleInputPassword1" name="password">
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1">再次确认密码</label>
                    <input type="password" class="form-control" id="exampleInputPassword1" name="password_confirm">
                </div>
                {#                <div class="form-group form-check">#}
                {#                    <input type="checkbox" class="form-check-input" id="exampleCheck1">#}
                {#                    <label class="form-check-label" for="exampleCheck1">Check me out</label>#}
                {#                </div>#}
                <button type="submit" class="btn btn-primary btn-block">Submit</button>

            </div>
            <div class="col-sm">

            </div>
        </div>
        </div>

    </form>

{% endblock %}